queue_rules:
  - name: default
    conditions:
      - base=main
      - label=ci:ready_to_merge
   
pull_request_rules:
  - name: push to default merge queue
    conditions:
      - base=main
      - label=ci:ready_to_merge
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
          {{ title }} [#{{ number }}](http://github.com/jwithers/citests/pull/{{ number }}) 
          {{ body_raw  }}

  - name: remove mergify label
    conditions:
      - merged
    actions:
      label:
        remove:
          - ci:ready_to_merge 

