name: called-inspect
on: workflow_call

jobs:
  dump_context:
    runs-on: ubuntu-latest
    name: Dump Github Context
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"