name: Caller Test

on:
  workflow_dispatch: {}

jobs:
  caller-1:
# and this is a random comment for testing.
    if: github.repository == 'jwithers/citests'
    uses: jwithers/citests/.github/workflows/called-1.yml@main
    with:
      var1: "hoopyfrood"
  show-var:
    runs-on: ubuntu-latest
    needs: caller-1
    steps:
      - name: showme
        run: |
          echo ${{ needs.caller-1.outputs.varout }}