name: create-issue
#on:
#  status
#  pull_request:
#    types: [labeled, synchronize]
#    types: [labeled]
      

jobs:
  make-issue:
    runs-on: ubuntu-latest
    if: |
      github.event.state  == 'error' ||
      github.event.state == 'failure'

    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo The status is: $DESCRIPTION
      - name: checkout repo
        uses: actions/checkout@v2
      - name: dump context
        run: |
          cat << OBJECT
          ${{ toJson(github.event) }}
          OBJECT
      - name: callout PR user
        run: echo ${{ github.event.pull_request.user.login }}
      - name: create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUM: ${{ github.event.number }}
          PR_LINK: ${{ github.event.pull_request._links.html.href }}
        with:
          assignees: ${{ github.event.pull_request.user.login }}
          filename: .github/ci-error-template.md