name: Inspect Github 

on:
  workflow_dispatch: {}
#  pull_request_target:
#    types: [synchronize]
#  pull_request_review:
#    types: [submitted]

jobs:
  dump-object:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: set-sha
        run: |
      - name: show-sha
        run: |
      
