name: Manual Job Failure

on:

  # Allow manually triggering the workflow.
  workflow_dispatch: {}

jobs:
  generate_integration_tests:
    runs-on: ubuntu-latest
    name: make it fail
    steps:
      - uses: actions/checkout@v2
      - name: Dump Github Context
        env: 
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: fail command
        run: exit 1

  issue-on-error:
    needs: [generate_integration_tests]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/issue_on_error.yml
    with:
      repo: ${{ github.repository }}
      workflow: ${{ github.workflow }}
      run_id: ${{ github.run_id }}
      run_number: ${{ github.run_number }}
      flag_label: ci:bot_issue
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

