name: Binary Size Log Test
name: test success check
on:
  workflow_dispatch: {}


jobs:
  test workflowrun check:
    runs-on: ubuntu-latest
    steps:

      - name: check workflowrun test
        if: ${{ github.event.workflow_run.conclusion=='success' }}
        run: |
          echo "this test shouldn't fire"

      - name: not workflowrun test
        if: ${{ !(github.event.workflow_run.conclusion=='success') }}
        run: |
